//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long CompId { get; set; }
        public string CompName { get; set; }
        public string CompAddress { get; set; }
        public string CompEmail { get; set; }
        public long CompPhone { get; set; }
    }
}
