//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long emp_id { get; set; }
        public string job_name { get; set; }
        public string Emp_name { get; set; }
        public string Email { get; set; }
        public decimal Salary { get; set; }
        public string Address { get; set; }
        public string dept_id { get; set; }
    }
}
