//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public string gread { get; set; }
        public decimal min_salary { get; set; }
        public decimal max_salary { get; set; }
        public long emp_id { get; set; }
    }
}
