//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudInfo
    {
        public long StudID { get; set; }
        public string StudName { get; set; }
        public string StudDept { get; set; }
        public string StudEmail { get; set; }
        public string StudLocation { get; set; }
    }
}
