//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.Models.DLA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Display(Name = "emp_id")]
        [Required(ErrorMessage = "Emp Id is Required")]
        public long emp_id { get; set; }


        [Required(ErrorMessage = "Job name is required")]
        [MaxLength(100)]
        public string job_name { get; set; }

        [Required(ErrorMessage = "Emp Name is required")]
        [MaxLength(100)]
        public string Emp_name { get; set; }


        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        public decimal Salary { get; set; }

        [Required(ErrorMessage = "Address is required")]
        [MaxLength(100)]
        public string Address { get; set; }

        [Display(Name = "dept_id")]
        [Required(ErrorMessage = "dept Id is Required")]
        public string dept_id { get; set; }
    }
}
