//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoredProcedure1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auther
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auther()
        {
            this.Books = new HashSet<Book>();
        }
    
        public long Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public int IPAddress { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
    }
}
