//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoredProcedure1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int StudantID { get; set; }
        public string SName { get; set; }
        public string SDept { get; set; }
        public string EmailID { get; set; }
        public string SLocation { get; set; }
    }
}
